# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, macOS, ARM64]

    steps:
    - uses: actions/checkout@v3
    - name: ShowDestinations
      run: xcodebuild -showdestinations -scheme swift-tca-dependency-reminders
    - name: ShowSdks
      run: xcodebuild -showsdks -scheme swift-tca-dependency-reminders
    - name: Build
      run: swift build -v
#      run: xcodebuild -scheme swift-tca-dependency-reminders -destination 'platform=OS X,arch=x86_64'
    - name: Run tests
      run: swift test -v
#      run: xcodebuild -scheme swift-tca-dependency-reminders -destination 'platform=OS X,arch=x86_64' test
